version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HundredDaysOfCloudWebsite-Dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-eqs40sdgkcq6"
s3_prefix = "100DaysOfCloudWebsite-Dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=\"100DaysOfCloudWebsite\""

